### ISSUE TITLE
Extension is not compatible with latest realurl version

### ISSUE THREAD

**Issue by tliegl** [CPS-IT/TYPO3-cps_stopdc#7]
When calling a page with active cps_stopdc extension on a TYPO3 7.6.15 and realurl 2.1.5 I get the error "Table 'tx_realurl_pathcache' doesn't exist." So maybe you could adjust the code to the newest realurl version.

**Comment by IchHabRecht** [comment]
Please do understand that cps_stopdc currently doesn't support TYPO3 7.6. You can resolves your realurl problem by switching off the realurl support in the extension settings

**Comment by tliegl** [comment]
Ok, didn't know that option. But this works in my case.

**Comment by IchHabRecht** [comment]
Would you mind to test the branch https://github.com/CPS-IT/TYPO3-cps_stopdc/tree/add-realurl2-support with the option enabled?

**Comment by tliegl** [comment]
Tested this branch with the realurl option enabled -> no error in frontend.
