### ISSUE TITLE
'No function named: CPSIT\CpsStopdc\Hooks\TypoScriptFrontendControllerHook' (73 chars)

### ISSUE THREAD

**Issue by AMartinNo1** [CPS-IT/TYPO3-cps_stopdc#8]
When having following setup:
1. TYPO3 CMS v7.6.15 with symlinks
2.  Using the revision [ef2fff71afb395c79144022159cff7811e73a8ef](https://github.com/CPS-IT/TYPO3-cps_stopdc/commit/ef2fff71afb395c79144022159cff7811e73a8ef)
3. Using realurl v2.1.5
4. PHP v5.6.30

I receive the debug message `'No function named: CPSIT\CpsStopdc\Hooks\TypoScriptFrontendControllerHook' (73 chars)` in frontend.

**Comment by AMartinNo1** [comment]
> Please do understand that cps_stopdc currently doesn't support TYPO3 7.6. You can resolves your realurl problem by switching off the realurl support in the extension settings

Do you know when realurl in TYPO3 v7.6.15 will be supported?

**Comment by IchHabRecht** [comment]
Do you mean cps_stopdc or realurl? We are currently working on making cps_stopdc compatible with the latest TYPO3 7.6 version

**Comment by AMartinNo1** [comment]
I am talking about cps_stopdc. Thanks for your fast response :)
